-- ============================================
-- MIGRAÇÃO COMPLETA: FATURAS
-- Storage bucket + Tabela de uploads
-- Rode no: Supabase > SQL Editor > New Query
-- ============================================

-- 1. CRIAR BUCKET DE STORAGE
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'faturas',
  'faturas',
  false,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- 2. POLICIES DO BUCKET
DROP POLICY IF EXISTS "Authenticated users can upload faturas" ON storage.objects;
CREATE POLICY "Authenticated users can upload faturas"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'faturas' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Users can view own faturas" ON storage.objects;
CREATE POLICY "Users can view own faturas"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'faturas' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Users can delete own faturas" ON storage.objects;
CREATE POLICY "Users can delete own faturas"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id = 'faturas' AND (storage.foldername(name))[1] = auth.uid()::text);

DROP POLICY IF EXISTS "Admin can view all faturas" ON storage.objects;
CREATE POLICY "Admin can view all faturas"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'faturas' AND EXISTS (
  SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
));

-- 3. (DEPRECIADO) faturas_upload foi substituída por invoice_uploads
--    A tabela invoice_uploads foi criada na migration 20260109_coupons_invoices.sql
--    Se você já rodou este script anteriormente e criou faturas_upload, pode removê-la:
--    DROP TABLE IF EXISTS faturas_upload;

-- ============================================
-- NOTIFICAÇÕES EM TEMPO REAL + LEMBRETES
-- ============================================

-- 1) Criar tabela de notificações
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('info', 'success', 'warning', 'error', 'payment', 'commission', 'lead')),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    link TEXT,
    read BOOLEAN DEFAULT false,
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    read_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id) WHERE read = false;

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own notifications" ON notifications;
CREATE POLICY "Users can view own notifications" ON notifications
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notifications" ON notifications;
CREATE POLICY "Users can update own notifications" ON notifications
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service can insert notifications" ON notifications;
CREATE POLICY "Service can insert notifications" ON notifications
    FOR INSERT WITH CHECK (true);

-- 2) Função auxiliar para criar notificação
CREATE OR REPLACE FUNCTION criar_notificacao(
    p_user_id UUID,
    p_type TEXT,
    p_title TEXT,
    p_message TEXT,
    p_link TEXT DEFAULT NULL,
    p_metadata JSONB DEFAULT NULL
) RETURNS BIGINT AS $$
DECLARE
    v_id BIGINT;
BEGIN
    INSERT INTO notifications (user_id, type, title, message, link, metadata)
    VALUES (p_user_id, p_type, p_title, p_message, p_link, p_metadata)
    RETURNING id INTO v_id;
    RETURN v_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3) Ativar realtime na tabela de notificações
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'notifications'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
    END IF;
END $$;

-- 4) Função de lembretes automáticos de fatura
CREATE OR REPLACE FUNCTION check_invoice_reminders()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO notifications (user_id, type, title, message, link, metadata)
    SELECT
        i.user_id,
        'warning',
        CASE
            WHEN i.vencimento::date = CURRENT_DATE THEN 'Fatura vence hoje!'
            WHEN i.vencimento::date = CURRENT_DATE + 1 THEN 'Fatura vence amanhã!'
            ELSE 'Fatura próxima do vencimento'
        END,
        CASE
            WHEN i.vencimento::date = CURRENT_DATE THEN 'Sua conta de energia no valor de R$ ' || ROUND(i.valor_total::numeric, 2)::text || ' vence hoje. Não deixe para depois!'
            WHEN i.vencimento::date = CURRENT_DATE + 1 THEN 'Sua conta de energia no valor de R$ ' || ROUND(i.valor_total::numeric, 2)::text || ' vence amanhã.'
            ELSE 'Sua conta de energia no valor de R$ ' || ROUND(i.valor_total::numeric, 2)::text || ' vence em ' || (i.vencimento::date - CURRENT_DATE)::text || ' dias.'
        END,
        '/dashboard/faturas/' || i.id,
        jsonb_build_object('invoice_id', i.id, 'vencimento', i.vencimento, 'valor', i.valor_total)
    FROM invoice_uploads i
    WHERE i.status = 'analyzed'
      AND i.vencimento IS NOT NULL
      AND i.vencimento::date BETWEEN CURRENT_DATE AND CURRENT_DATE + 3
      AND NOT EXISTS (
          SELECT 1 FROM notifications n
          WHERE n.user_id = i.user_id
            AND n.metadata->>'invoice_id' = i.id::text
            AND n.type = 'warning'
            AND n.created_at::date >= CURRENT_DATE - 1
      );
END;
$$;

-- 5) (OPCIONAL) Agendar execução diária — descomente se pg_cron estiver habilitado:
-- CREATE EXTENSION IF NOT EXISTS pg_cron;
-- SELECT cron.schedule('invoice-reminders', '0 8 * * *', 'SELECT check_invoice_reminders()');
