-- ============================================
-- SCHEMA COMPLETO - ENERGIALIVRE
-- Banco de dados otimizado para marketplace de energia solar
-- ============================================

-- Resetar sequências (opcional)
-- ALTER SEQUENCE profiles_id_seq RESTART WITH 1;
-- ALTER SEQUENCE leads_id_seq RESTART WITH 1;
-- ALTER SEQUENCE geradores_id_seq RESTART WITH 1;
-- ALTER SEQUENCE consumidor_id_seq RESTART WITH 1;
-- ALTER SEQUENCE assinaturas_id_seq RESTART WITH 1;
-- ALTER SEQUENCE comissoes_id_seq RESTART WITH 1;
-- ALTER SEQUENCE pagamentos_id_seq RESTART WITH 1;

-- ============================================
-- TABELA PRINCIPAL: PROFILES (PERFIS DE USUÁRIOS)
-- ============================================
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('consumidor', 'gerador', 'admin')),
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    whatsapp TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT true
);

-- Índices para performance
CREATE INDEX idx_profiles_tipo ON profiles(tipo);
CREATE INDEX idx_profiles_role ON profiles(role);
CREATE INDEX idx_profiles_cidade ON profiles(cidade);
CREATE INDEX idx_profiles_estado ON profiles(estado);

-- ============================================
-- TABELA: LEADS (OPORTUNIDADES DE NEGÓCIO)
-- ============================================
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('consumidor', 'gerador')),
    capacidade_kwp FLOAT, -- Apenas para geradores
    gasto_mensal FLOAT, -- Apenas para consumidores
    concessionaria TEXT, -- Apenas para geradores
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'recusado')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    processed_by UUID REFERENCES profiles(id),
    observacoes TEXT
);

-- Índices para performance
CREATE INDEX idx_leads_status ON leads(status);
CREATE INDEX idx_leads_tipo ON leads(tipo);
CREATE INDEX idx_leads_cidade ON leads(cidade);
CREATE INDEX idx_leads_estado ON leads(estado);
CREATE INDEX idx_leads_created_at ON leads(created_at DESC);
CREATE INDEX idx_leads_user_id ON leads(user_id);

-- ============================================
-- TABELA: GERADORES (USUÁRIOS QUE GERAÇÃO ENERGIA)
-- ============================================
CREATE TABLE IF NOT EXISTS geradores (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    nome_usina TEXT NOT NULL,
    capacidade_kwp FLOAT NOT NULL CHECK (capacidade_kwp > 0),
    excedente_mensal_kwh FLOAT NOT NULL CHECK (excedente_mensal_kwh > 0),
    concessionaria TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    endereco TEXT,
    latitude FLOAT,
    longitude FLOAT,
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'ativo', 'inativo')),
    data_aprovacao TIMESTAMPTZ,
    lucro_total DECIMAL(12,2) DEFAULT 0.00,
    kwh_vendidos_total INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX idx_geradores_status ON geradores(status);
CREATE INDEX idx_geradores_concessionaria ON geradores(concessionaria);
CREATE INDEX idx_geradores_cidade ON geradores(cidade);
CREATE INDEX idx_geradores_capacidade ON geradores(capacidade_kwp);
CREATE INDEX idx_geradores_excedente ON geradores(excedente_mensal_kwh);

-- ============================================
-- TABELA: CONSUMIDORES (USUÁRIOS QUE CONSUMEM ENERGIA)
-- ============================================
CREATE TABLE IF NOT EXISTS consumidores (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    gasto_mensal FLOAT NOT NULL CHECK (gasto_mensal > 0),
    economia_mensal DECIMAL(10,2) DEFAULT 0.00,
    economia_total DECIMAL(12,2) DEFAULT 0.00,
    kwh_consumidos INTEGER DEFAULT 0,
    co2_evitado_kg INTEGER DEFAULT 0,
    arvores_salvas INTEGER DEFAULT 0,
    plano_ativo BOOLEAN DEFAULT false,
    data_primeira_assinatura TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX idx_consumidores_gasto_mensal ON consumidores(gasto_mensal);
CREATE INDEX idx_consumidores_plano_ativo ON consumidores(plano_ativo);

-- ============================================
-- TABELA: ASSINATURAS (PLANOS DE CONSUMIDORES)
-- ============================================
CREATE TABLE IF NOT EXISTS assinaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    stripe_subscription_id TEXT UNIQUE NOT NULL,
    stripe_price_id TEXT NOT NULL,
    nome_plano TEXT NOT NULL,
    valor_mensal DECIMAL(10,2) NOT NULL,
    kwh_mensais INTEGER NOT NULL,
    economia_percentual INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'past_due', 'canceled', 'unpaid')),
    current_period_start TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ NOT NULL,
    cancel_at_period_end BOOLEAN DEFAULT false,
    trial_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    canceled_at TIMESTAMPTZ
);

-- Índices para performance
CREATE INDEX idx_assinaturas_user_id ON assinaturas(user_id);
CREATE INDEX idx_assinaturas_stripe_subscription_id ON assinaturas(stripe_subscription_id);
CREATE INDEX idx_assinaturas_status ON assinaturas(status);
CREATE INDEX idx_assinaturas_period_end ON assinaturas(current_period_end);

-- ============================================
-- TABELA: COMISSÕES (SISTEMA DE EMBaixADORES)
-- ============================================
CREATE TABLE IF NOT EXISTS comissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embaixador_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    cliente_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    valor_comissao DECIMAL(10,2) NOT NULL,
    percentual INTEGER NOT NULL CHECK (percentual > 0 AND percentual <= 100),
    tipo_comissao TEXT NOT NULL CHECK (tipo_comissao IN ('cadastro', 'recorrente')),
    status_pagamento TEXT NOT NULL DEFAULT 'pendente' CHECK (status_pagamento IN ('pendente', 'pago', 'cancelado')),
    data_pagamento TIMESTAMPTZ,
    stripe_payment_intent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mes_referencia DATE NOT NULL,
    ano_referencia INTEGER NOT NULL
);

-- Índices para performance
CREATE INDEX idx_comissoes_embaixador_id ON comissoes(embaixador_id);
CREATE INDEX idx_comissoes_cliente_id ON comissoes(cliente_id);
CREATE INDEX idx_comissoes_lead_id ON comissoes(lead_id);
CREATE INDEX idx_comissoes_status_pagamento ON comissoes(status_pagamento);
CREATE INDEX idx_comissoes_tipo_comissao ON comissoes(tipo_comissao);
CREATE INDEX idx_comissoes_data_pagamento ON comissoes(data_pago);
CREATE INDEX idx_comissoes_mes_ano ON comissoes(mes_referencia, ano_referencia);

-- ============================================
-- TABELA: PAGAMENTOS (HISTÓRICO FINANCEIRO)
-- ============================================
CREATE TABLE IF NOT EXISTS pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tipo_pagamento TEXT NOT NULL CHECK (tipo_pagamento IN ('assinatura', 'comissao', 'adicional')),
    valor DECIMAL(10,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
    stripe_payment_intent TEXT UNIQUE,
    stripe_charge_id TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

-- Índices para performance
CREATE INDEX idx_pagamentos_user_id ON pagamentos(user_id);
CREATE INDEX idx_pagamentos_tipo_pagamento ON pagamentos(tipo_pagamento);
CREATE INDEX idx_pagamentos_status ON pagamentos(status);
CREATE INDEX idx_pagamentos_created_at ON pagamentos(created_at DESC);

-- ============================================
-- TABELA: MATCHES (CONEXÕES ENTRE GERADORES E CONSUMIDORES)
-- ============================================
CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gerador_id UUID REFERENCES geradores(id) ON DELETE CASCADE,
    consumidor_id UUID REFERENCES consumidores(id) ON DELETE CASCADE,
    kwh_alocados INTEGER NOT NULL,
    valor_transacao DECIMAL(10,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed', 'cancelled')),
    data_inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_fim TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX idx_matches_gerador_id ON matches(gerador_id);
CREATE INDEX idx_matches_consumidor_id ON matches(consumidor_id);
CREATE INDEX idx_matches_status ON matches(status);
CREATE INDEX idx_matches_data_inicio ON matches(data_inicio);

-- ============================================
-- TABELA: RELATÓRIOS (PERFORMANCE DO SISTEMA)
-- ============================================
CREATE TABLE IF NOT EXISTS relatorios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_relatorio TEXT NOT NULL CHECK (tipo_relatorio IN ('financeiro', 'operacional', 'usuario')),
    periodo DATE NOT NULL,
    dados JSONB NOT NULL,
    gerado_por UUID REFERENCES profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX idx_relatorios_tipo_periodo ON relatorios(tipo_relatorio, periodo);
CREATE INDEX idx_relatorios_criado_em ON relatorios(created_at DESC);

-- ============================================
-- FUNÇÕES TRIGGER (AUTOMAÇÃO)
-- ============================================

-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers para atualizar updated_at
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_geradores_updated_at BEFORE UPDATE ON geradores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_consumidores_updated_at BEFORE UPDATE ON consumidores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_assinaturas_updated_at BEFORE UPDATE ON assinaturas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_comissoes_updated_at BEFORE UPDATE ON comissoes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pagamentos_updated_at BEFORE UPDATE ON pagamentos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Função para criar perfil automaticamente quando novo usuário se cadastra
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, nome, tipo, role, whatsapp, cidade, estado)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'nome', NEW.email),
        COALESCE(NEW.raw_user_meta_data->>'tipo', 'consumidor'),
        'user',
        COALESCE(NEW.raw_user_meta_data->>'whatsapp', ''),
        COALESCE(NEW.raw_user_meta_data->>'cidade', ''),
        COALESCE(NEW.raw_user_meta_data->>'estado', '')
    );
    
    -- Criar entry correspondente na tabela específica (gerador ou consumidor)
    IF COALESCE(NEW.raw_user_meta_data->>'tipo', 'consumidor') = 'gerador' THEN
        INSERT INTO public.geradores (id, nome_usina, capacidade_kwp, excedente_mensal_kwh, concessionaria, cidade, estado, status)
        VALUES (
            NEW.id,
            COALESCE(NEW.raw_user_meta_data->>'nome_usina', 'Usina Solar'),
            COALESCE(NEW.raw_user_meta_data->>'capacidade_kwp', 0)::FLOAT,
            COALESCE(NEW.raw_user_meta_data->>'excedente_mensal_kwh', 0)::FLOAT,
            COALESCE(NEW.raw_user_meta_data->>'concessionaria', ''),
            COALESCE(NEW.raw_user_meta_data->>'cidade', ''),
            COALESCE(NEW.raw_user_meta_data->>'estado', ''),
            'pendente'
        );
    ELSE
        INSERT INTO public.consumidores (id, gasto_mensal)
        VALUES (
            NEW.id,
            COALESCE(NEW.raw_user_meta_data->>'gasto_mensal', 0)::FLOAT
        );
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para criar perfil automaticamente
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================
-- ROW LEVEL SECURITY (RLS) - SEGURANÇA ABSOLUTA
-- ============================================

-- Habilitar RLS para todas as tabelas
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE geradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE consumidores ENABLE ROW LEVEL SECURITY;
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE comissoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE relatorios ENABLE ROW LEVEL SECURITY;

-- Política para profiles: usuários só podem ver seu próprio perfil
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles
    FOR UPDATE USING (auth.uid() = id);

-- Política para admin: admin pode ver tudo
DROP POLICY IF EXISTS "Admin can view all profiles" ON profiles;
CREATE POLICY "Admin can view all profiles" ON profiles
    FOR ALL USING (
        auth.role() = 'admin' OR
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para leads: usuários podem ver seus próprios leads, admin pode ver tudo
DROP POLICY IF EXISTS "Users can view own leads" ON leads;
CREATE POLICY "Users can view own leads" ON leads
    FOR SELECT USING (
        auth.uid() = user_id OR
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

DROP POLICY IF EXISTS "Admin can manage all leads" ON leads;
CREATE POLICY "Admin can manage all leads" ON leads
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para geradores: usuários podem ver seus próprios geradores, admin pode ver tudo
DROP POLICY IF EXISTS "Users can view own geradores" ON geradores;
CREATE POLICY "Users can view own geradores" ON geradores
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admin can view all geradores" ON geradores;
CREATE POLICY "Admin can view all geradores" ON geradores
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para consumidores: usuários podem ver seus próprios consumidores, admin pode ver tudo
DROP POLICY IF EXISTS "Users can view own consumidores" ON consumidores;
CREATE POLICY "Users can view own consumidores" ON consumidores
    FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admin can view all consumidores" ON consumidores;
CREATE POLICY "Admin can view all consumidores" ON consumidores
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para assinaturas: usuários podem ver suas próprias assinaturas, admin pode ver tudo
DROP POLICY IF EXISTS "Users can view own assinaturas" ON assinaturas;
CREATE POLICY "Users can view own assinaturas" ON assinaturas
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin can view all assinaturas" ON assinaturas;
CREATE POLICY "Admin can view all assinaturas" ON assinaturas
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para comissões: embaixadores podem ver suas comissões, admin pode ver tudo
DROP POLICY IF EXISTS "Embaixadores can view own commissions" ON comissoes;
CREATE POLICY "Embaixadores can view own commissions" ON comissoes
    FOR SELECT USING (auth.uid() = embaixador_id);

DROP POLICY IF EXISTS "Admin can view all commissions" ON comissoes;
CREATE POLICY "Admin can view all commissions" ON comissoes
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para pagamentos: usuários podem ver seus próprios pagamentos, admin pode ver tudo
DROP POLICY IF EXISTS "Users can view own payments" ON pagamentos;
CREATE POLICY "Users can view own payments" ON pagamentos
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin can view all payments" ON pagamentos;
CREATE POLICY "Admin can view all payments" ON pagamentos
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para matches: usuários podem ver seus próprios matches, admin pode ver tudo
DROP POLICY IF EXISTS "Users can view own matches" ON matches;
CREATE POLICY "Users can view own matches" ON matches
    FOR SELECT USING (
        auth.uid() = gerador_id OR 
        auth.uid() = consumidor_id
    );

DROP POLICY IF EXISTS "Admin can view all matches" ON matches;
CREATE POLICY "Admin can view all matches" ON matches
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Política para relatórios: apenas admin pode acessar
DROP POLICY IF EXISTS "Admin can view reports" ON relatorios;
CREATE POLICY "Admin can view reports" ON relatorios
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- ============================================
-- VIEWS ÚTEIS (CONSULTAS COMPLEXAS)
-- ============================================

-- View de estatísticas do sistema
CREATE OR REPLACE VIEW view_estatisticas_sistema AS
SELECT 
    COUNT(DISTINCT p.id) as total_usuarios,
    COUNT(DISTINCT CASE WHEN p.tipo = 'gerador' THEN p.id END) as total_geradores,
    COUNT(DISTINCT CASE WHEN p.tipo = 'consumidor' THEN p.id END) as total_consumidores,
    COUNT(DISTINCT l.id) as total_leads,
    COUNT(DISTINCT CASE WHEN l.status = 'aprovado' THEN l.id END) as leads_aprovados,
    COUNT(DISTINCT a.id) as assinaturas_ativas,
    COALESCE(SUM(a.valor_mensal), 0) as faturamento_mensal,
    COALESCE(SUM(c.valor_comissao), 0) as total_comissoes,
    COALESCE(SUM(m.valor_transacao), 0) as volume_transacoes
FROM profiles p
LEFT JOIN leads l ON p.id = l.user_id
LEFT JOIN assinaturas a ON p.id = a.user_id AND a.status = 'active'
LEFT JOIN comissoes c ON p.id = c.embaixador_id AND c.status_pagamento = 'pago'
LEFT JOIN matches m ON p.id = m.gerador_id AND m.status = 'active';

-- View de comissões pendentes
CREATE OR REPLACE VIEW view_comissoes_pendentes AS
SELECT 
    c.*,
    p.nome as embaixador_nome,
    p.email as embaixador_email,
    cli.nome as cliente_nome,
    cli.email as cliente_email
FROM comissoes c
JOIN profiles p ON c.embaixador_id = p.id
LEFT JOIN auth.users cli ON c.cliente_id = cli.id
WHERE c.status_pagamento = 'pendente';

-- View de performance de geradores
CREATE OR REPLACE VIEW view_performance_geradores AS
SELECT 
    g.id,
    g.nome_usina,
    g.capacidade_kwp,
    g.excedente_mensal_kwh,
    g.status,
    g.lucro_total,
    g.kwh_vendidos_total,
    COUNT(m.id) as total_matches,
    COALESCE(SUM(m.valor_transacao), 0) as receita_total,
    COUNT(DISTINCT a.id) as assinaturas_geradas
FROM geradores g
LEFT JOIN matches m ON g.id = m.gerador_id AND m.status = 'active'
LEFT JOIN assinaturas a ON m.consumidor_id = a.user_id AND a.status = 'active'
GROUP BY g.id, g.nome_usina, g.capacidade_kwp, g.excedente_mensal_kwh, g.status, g.lucro_total, g.kwh_vendidos_total;

-- ============================================
-- FUNÇÕES UTILITÁRIAS
-- ============================================

-- Função para calcular comissão de cadastro
CREATE OR REPLACE FUNCTION calcular_comissao_cadastro(
    valor_plano DECIMAL(10,2),
    percentual_comissao INTEGER
) RETURNS DECIMAL(10,2) AS $$
BEGIN
    RETURN (valor_plano * percentual_comissao) / 100;
END;
$$ LANGUAGE plpgsql;

-- Função para calcular comissão recorrente
CREATE OR REPLACE FUNCTION calcular_comissao_recorrente(
    valor_assinatura DECIMAL(10,2),
    percentual_comissao INTEGER
) RETURNS DECIMAL(10,2) AS $$
BEGIN
    RETURN (valor_assinatura * percentual_comissao) / 100;
END;
$$ LANGUAGE plpgsql;

-- Função para atualizar estatísticas de consumidor
CREATE OR REPLACE FUNCTION atualizar_estatisticas_consumidor(
    consumidor_id UUID,
    gasto_mensal FLOAT,
    economia_mensal DECIMAL(10,2)
) RETURNS VOID AS $$
BEGIN
    UPDATE consumidores 
    SET 
        gasto_mensal = gasto_mensal,
        economia_mensal = economia_mensal,
        economia_total = economia_total + economia_mensal,
        kwh_consumidos = kwh_consumidos + (gasto_mensal * 0.8), -- Estimativa
        co2_evitado_kg = co2_evitado_kg + (gasto_mensal * 0.7), -- Estimativa
        arvores_salvas = arvores_salvas + (gasto_mensal * 0.01) -- Estimativa
    WHERE id = consumidor_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- PERMISSÕES DE BANCO DE DADOS
-- ============================================

-- Conceder permissões para o serviço authenticated (usuários logados)
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON view_estatisticas_sistema TO authenticated;
GRANT SELECT ON view_comissoes_pendentes TO authenticated;
GRANT SELECT ON view_performance_geradores TO authenticated;

-- Conceder permissões para o serviço anonymous (visitantes)
GRANT USAGE ON SCHEMA public TO anonymous;
GRANT SELECT ON view_estatisticas_sistema TO anonymous;

-- ============================================
-- ÍNDICES ADICIONAIS PARA PERFORMANCE
-- ============================================

-- Índices compostos para consultas complexas
CREATE INDEX idx_leads_tipo_status ON leads(tipo, status);
CREATE INDEX idx_comissoes_embaixador_status ON comissoes(embaixador_id, status_pagamento);
CREATE INDEX idx_assinaturas_status_period ON assinaturas(status, current_period_end);
CREATE INDEX idx_matches_gerador_status ON matches(gerador_id, status);

-- Índices para busca full-text (opcional)
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- CREATE INDEX idx_leads_nome_trgm ON leads USING gin (nome gin_trgm_ops);
-- CREATE INDEX idx_leads_cidade_trgm ON leads USING gin (cidade gin_trgm_ops);