-- ============================================
-- MIGRATION 20260104: MATCH GEORREFERENCIADO + MEMBER PLUS
-- EnergiaLivre v2.1
-- ============================================
-- Adiciona:
--   * user_locations (lat/lng por usuário)
--   * match_proposals (propostas de match)
--   * Colunas member_plus em profiles
--   * Colunas latitude/longitude em leads
--   * RLS policies
-- ============================================

-- ============================================
-- 1. TABELA: USER_LOCATIONS (LOCALIZAÇÃO DOS USUÁRIOS)
-- ============================================

CREATE TABLE IF NOT EXISTS user_locations (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL CHECK (lat >= -90 AND lat <= 90),
    lng DOUBLE PRECISION NOT NULL CHECK (lng >= -180 AND lng <= 180),
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    accuracy_meters INTEGER,
    source TEXT NOT NULL DEFAULT 'browser' CHECK (source IN ('browser', 'geocoded', 'manual')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_locations_cidade ON user_locations(cidade);
CREATE INDEX IF NOT EXISTS idx_user_locations_estado ON user_locations(estado);
CREATE INDEX IF NOT EXISTS idx_user_locations_lat_lng ON user_locations(lat, lng);

DROP TRIGGER IF EXISTS update_user_locations_updated_at ON user_locations;
CREATE TRIGGER update_user_locations_updated_at
    BEFORE UPDATE ON user_locations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE user_locations ENABLE ROW LEVEL SECURITY;

-- Owner pode ver e atualizar sua própria localização
DROP POLICY IF EXISTS "Users can view own location" ON user_locations;
CREATE POLICY "Users can view own location" ON user_locations
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own location" ON user_locations;
CREATE POLICY "Users can insert own location" ON user_locations
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own location" ON user_locations;
CREATE POLICY "Users can update own location" ON user_locations
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own location" ON user_locations;
CREATE POLICY "Users can delete own location" ON user_locations
    FOR DELETE USING (auth.uid() = user_id);

-- Qualquer usuário autenticado pode ler localizações de outros (para match)
DROP POLICY IF EXISTS "Authenticated users can view all locations" ON user_locations;
CREATE POLICY "Authenticated users can view all locations" ON user_locations
    FOR SELECT TO authenticated USING (true);

-- Admin pode tudo (verifica tabela admins separada)
DROP POLICY IF EXISTS "Admin can manage all locations" ON user_locations;
CREATE POLICY "Admin can manage all locations" ON user_locations
    FOR ALL USING (
        EXISTS (SELECT 1 FROM admins WHERE id = auth.uid())
    );

-- ============================================
-- 2. TABELA: MATCH_PROPOSALS (PROPOSTAS DE MATCH)
-- ============================================

CREATE TABLE IF NOT EXISTS match_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    to_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    gerador_id UUID REFERENCES geradores(id) ON DELETE CASCADE,
    consumidor_id UUID REFERENCES consumidores(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'expired', 'cancelled')),
    message TEXT,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
    responded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT no_self_proposal CHECK (from_user_id != to_user_id)
);

CREATE INDEX IF NOT EXISTS idx_match_proposals_from ON match_proposals(from_user_id);
CREATE INDEX IF NOT EXISTS idx_match_proposals_to ON match_proposals(to_user_id);
CREATE INDEX IF NOT EXISTS idx_match_proposals_status ON match_proposals(status);
CREATE INDEX IF NOT EXISTS idx_match_proposals_expires ON match_proposals(expires_at);
CREATE INDEX IF NOT EXISTS idx_match_proposals_gerador ON match_proposals(gerador_id);
CREATE INDEX IF NOT EXISTS idx_match_proposals_consumidor ON match_proposals(consumidor_id);
CREATE INDEX IF NOT EXISTS idx_match_proposals_unique_pending
    ON match_proposals(from_user_id, to_user_id)
    WHERE status = 'pending';

DROP TRIGGER IF EXISTS update_match_proposals_updated_at ON match_proposals;
CREATE TRIGGER update_match_proposals_updated_at
    BEFORE UPDATE ON match_proposals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE match_proposals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own proposals" ON match_proposals;
CREATE POLICY "Users can view own proposals" ON match_proposals
    FOR SELECT USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

DROP POLICY IF EXISTS "Users can create proposals" ON match_proposals;
CREATE POLICY "Users can create proposals" ON match_proposals
    FOR INSERT WITH CHECK (auth.uid() = from_user_id);

DROP POLICY IF EXISTS "Receivers can update proposal status" ON match_proposals;
CREATE POLICY "Receivers can update proposal status" ON match_proposals
    FOR UPDATE USING (auth.uid() = to_user_id OR auth.uid() = from_user_id);

DROP POLICY IF EXISTS "Senders can cancel pending proposals" ON match_proposals;
CREATE POLICY "Senders can cancel pending proposals" ON match_proposals
    FOR DELETE USING (auth.uid() = from_user_id AND status = 'pending');

DROP POLICY IF EXISTS "Admin can manage all proposals" ON match_proposals;
CREATE POLICY "Admin can manage all proposals" ON match_proposals
    FOR ALL USING (
        EXISTS (SELECT 1 FROM admins WHERE id = auth.uid())
    );

-- ============================================
-- 3. ADICIONAR COLUNAS MEMBER_PLUS EM PROFILES
-- ============================================

ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS member_plus_active BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS member_plus_activated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS member_plus_expires_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_profiles_member_plus
    ON profiles(member_plus_active)
    WHERE member_plus_active = true;

-- ============================================
-- 4. ADICIONAR LATITUDE/LONGITUDE EM LEADS
-- ============================================

ALTER TABLE leads
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

-- ============================================
-- 5. FUNÇÃO RPC: FIND_MATCH_CANDIDATES
-- ============================================
-- Retorna candidatos (usuários do tipo oposto) dentro de um raio em km
-- Usa fórmula de Haversine para cálculo de distância

CREATE OR REPLACE FUNCTION find_match_candidates(
    p_user_id UUID,
    p_user_lat DOUBLE PRECISION,
    p_user_lng DOUBLE PRECISION,
    p_target_tipo TEXT,
    p_radius_km INTEGER DEFAULT 50,
    p_limit INTEGER DEFAULT 50
)
RETURNS TABLE (
    user_id UUID,
    nome TEXT,
    cidade TEXT,
    estado TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    distance_km DOUBLE PRECISION,
    tipo TEXT,
    is_member_plus BOOLEAN
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.id,
        p.nome,
        ul.cidade,
        ul.estado,
        ul.lat,
        ul.lng,
        (
            6371 * acos(
                LEAST(1.0, GREATEST(-1.0,
                    cos(radians(p_user_lat)) * cos(radians(ul.lat)) *
                    cos(radians(ul.lng) - radians(p_user_lng)) +
                    sin(radians(p_user_lat)) * sin(radians(ul.lat))
                ))
            )
        )::DOUBLE PRECISION AS distance_km,
        p.tipo,
        p.member_plus_active
    FROM profiles p
    JOIN user_locations ul ON ul.user_id = p.id
    WHERE p.id != p_user_id
      AND p.tipo = p_target_tipo
      AND p.is_active = true
      AND (
          6371 * acos(
              LEAST(1.0, GREATEST(-1.0,
                  cos(radians(p_user_lat)) * cos(radians(ul.lat)) *
                  cos(radians(ul.lng) - radians(p_user_lng)) +
                  sin(radians(p_user_lat)) * sin(radians(ul.lat))
              ))
          )
      ) <= p_radius_km
    ORDER BY distance_km ASC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql STABLE;

-- ============================================
-- 6. FUNÇÃO: AUTO-EXPIRAR PROPOSTAS
-- ============================================

CREATE OR REPLACE FUNCTION expire_old_proposals() RETURNS VOID AS $$
BEGIN
    UPDATE match_proposals
    SET status = 'expired',
        updated_at = NOW()
    WHERE status = 'pending'
      AND expires_at < NOW();
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 7. COMENTÁRIOS
-- ============================================

COMMENT ON TABLE user_locations IS 'Localização georreferenciada (lat/lng) de cada usuário. Usada pelo sistema de match.';
COMMENT ON TABLE match_proposals IS 'Propostas de match entre usuários. Status: pending/accepted/rejected/expired/cancelled.';
COMMENT ON COLUMN profiles.member_plus_active IS 'Flag de ativação do plano Member Plus (R$ 9,99/mês).';
COMMENT ON COLUMN profiles.member_plus_expires_at IS 'Data de expiração do Member Plus.';
COMMENT ON FUNCTION find_match_candidates IS 'Retorna usuários do tipo oposto dentro de um raio geográfico (Haversine).';
COMMENT ON FUNCTION expire_old_proposals IS 'Marca propostas pendentes como expired quando ultrapassam expires_at.';
