-- ============================================
-- MIGRATION 20260103: CRIAR TABELA ASSINATURAS
-- EnergiaLivre v2.1
-- ============================================
-- A tabela `assinaturas` está referenciada pelo webhook do Stripe
-- (app/api/stripe/webhook/route.ts) e pelo admin dashboard, mas
-- não foi criada no schema aplicado (provavelmente rodou só parte
-- do schema.sql). Esta migration cria a tabela foundation.
--
-- Diferenças em relação ao schema.sql original:
--   * kwh_mensais: agora NULLABLE (gerador/member_plus não têm kWh)
--   * economia_percentual: agora NULLABLE (mesma razão)
--   * Inclui colunas tipo_plano e capacidade_kwp que estavam
--     na migration 20260106 (agora redundant; migration 20260106
--     fica como no-op idempotente)
--   * RLS habilitada com policies (o original não tinha)
-- ============================================

CREATE TABLE IF NOT EXISTS assinaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    stripe_subscription_id TEXT UNIQUE NOT NULL,
    stripe_price_id TEXT NOT NULL,
    nome_plano TEXT NOT NULL,
    valor_mensal DECIMAL(10,2) NOT NULL,

    -- Campos do plano consumidor (nullable para gerador/member_plus)
    kwh_mensais INTEGER,
    economia_percentual INTEGER,

    -- Campos novos (migration 20260106 incorporada)
    tipo_plano TEXT NOT NULL DEFAULT 'consumidor'
        CHECK (tipo_plano IN ('consumidor', 'gerador', 'member_plus')),
    capacidade_kwp INTEGER,

    -- Status e períodos
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'past_due', 'canceled', 'unpaid')),
    current_period_start TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ NOT NULL,
    cancel_at_period_end BOOLEAN NOT NULL DEFAULT false,
    trial_end TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,

    -- Auditoria
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_assinaturas_user_id
    ON assinaturas(user_id);
CREATE INDEX IF NOT EXISTS idx_assinaturas_stripe_subscription_id
    ON assinaturas(stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_assinaturas_status
    ON assinaturas(status);
CREATE INDEX IF NOT EXISTS idx_assinaturas_period_end
    ON assinaturas(current_period_end);
CREATE INDEX IF NOT EXISTS idx_assinaturas_tipo_plano
    ON assinaturas(tipo_plano);
CREATE INDEX IF NOT EXISTS idx_assinaturas_user_tipo_status
    ON assinaturas(user_id, tipo_plano, status);

-- Trigger de updated_at
DROP TRIGGER IF EXISTS update_assinaturas_updated_at ON assinaturas;
CREATE TRIGGER update_assinaturas_updated_at
    BEFORE UPDATE ON assinaturas
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- RLS
-- ============================================
-- O webhook usa createServerClient (sem service_role). Stripe
-- bate no webhook sem cookies do user, então a sessão é "anon".
-- Para o webhook conseguir inserir, a policy permite INSERT
-- anônimo. SELECT/UPDATE ficam restritos ao dono.
-- ============================================
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own assinaturas" ON assinaturas;
CREATE POLICY "Users can view own assinaturas" ON assinaturas
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own assinaturas" ON assinaturas;
CREATE POLICY "Users can update own assinaturas" ON assinaturas
    FOR UPDATE USING (auth.uid() = user_id);

-- Webhook precisa inserir sem user context (anon). Permitido.
-- Em produção ideal, isso seria via service_role + RPC.
DROP POLICY IF EXISTS "Allow anonymous insert (webhook)" ON assinaturas;
CREATE POLICY "Allow anonymous insert (webhook)" ON assinaturas
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admin can manage all assinaturas" ON assinaturas;
CREATE POLICY "Admin can manage all assinaturas" ON assinaturas
    FOR ALL USING (
        EXISTS (SELECT 1 FROM admins WHERE id = auth.uid())
    );

-- Comentários
COMMENT ON TABLE assinaturas IS 'Assinaturas de planos (consumidor, gerador, member_plus).';
COMMENT ON COLUMN assinaturas.tipo_plano IS
    'consumidor | gerador | member_plus';
COMMENT ON COLUMN assinaturas.kwh_mensais IS
    'kWh mensais. NULL para gerador/member_plus.';
COMMENT ON COLUMN assinaturas.economia_percentual IS
    'Economia %. NULL para gerador/member_plus.';
COMMENT ON COLUMN assinaturas.capacidade_kwp IS
    'kWp. Preenchido para tipo_plano=gerador.';
