-- =====================================================
-- ENERGIALIVRE — Migration 20260112 (FASE C.2 CONSOLIDADA)
-- Cole no Supabase SQL Editor → New query → Run
-- =====================================================
-- Migration consolidada (bootstrap tabelas faltantes + Fase C.2)
-- aplicada manualmente em 2026-06-05. Idempotente.
-- Cria:
--   * 9 tabelas core (profiles, leads, geradores, consumidores,
--     assinaturas, comissoes, pagamentos, matches, admins)
--   * 1 tabela Fase C.2 (payment_agreements)
--   * 3 RPCs (record_payment_agreement, process_match_commissions,
--     process_payment_commissions)
--   * RLS + indices + triggers
-- Dependencias (rodar ANTES se ainda nao existirem):
--   * 20260105_match_member_plus.sql  (match_proposals, user_locations)
--   * 20260107_coin_system.sql       (coin_wallet, credit_wallet)
--   * 20260109_coupons_invoices.sql  (coupons, invoice_uploads)
-- =====================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('consumidor', 'gerador', 'parceiro', 'admin')),
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    whatsapp TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('consumidor', 'gerador', 'parceiro')),
    capacidade_kwp FLOAT,
    gasto_mensal FLOAT,
    concessionaria TEXT,
    nicho TEXT,
    audiencia_estimada INTEGER,
    canal TEXT,
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'recusado')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    processed_by UUID REFERENCES profiles(id),
    observacoes TEXT,
    embaixador_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS geradores (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    nome_usina TEXT NOT NULL,
    capacidade_kwp FLOAT NOT NULL CHECK (capacidade_kwp > 0),
    excedente_mensal_kwh FLOAT NOT NULL CHECK (excedente_mensal_kwh > 0),
    concessionaria TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    endereco TEXT,
    latitude FLOAT,
    longitude FLOAT,
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'ativo', 'inativo')),
    data_aprovacao TIMESTAMPTZ,
    lucro_total DECIMAL(12,2) DEFAULT 0.00,
    kwh_vendidos_total INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS consumidores (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    gasto_mensal FLOAT NOT NULL CHECK (gasto_mensal > 0),
    economia_mensal DECIMAL(10,2) DEFAULT 0.00,
    economia_total DECIMAL(12,2) DEFAULT 0.00,
    kwh_consumidos INTEGER DEFAULT 0,
    co2_evitado_kg INTEGER DEFAULT 0,
    arvores_salvas INTEGER DEFAULT 0,
    plano_ativo BOOLEAN DEFAULT false,
    data_primeira_assinatura TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assinaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    stripe_subscription_id TEXT UNIQUE NOT NULL,
    stripe_price_id TEXT NOT NULL,
    nome_plano TEXT NOT NULL,
    valor_mensal DECIMAL(10,2) NOT NULL,
    kwh_mensais INTEGER NOT NULL,
    economia_percentual INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'past_due', 'canceled', 'unpaid')),
    current_period_start TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ NOT NULL,
    cancel_at_period_end BOOLEAN DEFAULT false,
    trial_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    canceled_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS comissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embaixador_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    cliente_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    valor_comissao DECIMAL(10,2) NOT NULL,
    percentual INTEGER NOT NULL CHECK (percentual > 0 AND percentual <= 100),
    tipo_comissao TEXT NOT NULL CHECK (tipo_comissao IN ('cadastro', 'recorrente', 'match', 'embaixador_5pct', 'ufv_15pct')),
    status_pagamento TEXT NOT NULL DEFAULT 'pendente' CHECK (status_pagamento IN ('pendente', 'pago', 'cancelado')),
    data_pagamento TIMESTAMPTZ,
    stripe_payment_intent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mes_referencia DATE NOT NULL DEFAULT date_trunc('month', NOW())::date,
    ano_referencia INTEGER NOT NULL DEFAULT EXTRACT(year FROM NOW())::integer
);

CREATE TABLE IF NOT EXISTS pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tipo_pagamento TEXT NOT NULL CHECK (tipo_pagamento IN ('assinatura', 'comissao', 'adicional')),
    valor DECIMAL(10,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
    stripe_payment_intent TEXT UNIQUE,
    stripe_charge_id TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gerador_id UUID REFERENCES geradores(id) ON DELETE CASCADE,
    consumidor_id UUID REFERENCES consumidores(id) ON DELETE CASCADE,
    kwh_alocados INTEGER NOT NULL,
    valor_transacao DECIMAL(10,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed', 'cancelled')),
    data_inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_fim TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admins (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_agreements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    terms_version TEXT NOT NULL,
    terms_hash TEXT NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip_address INET,
    user_agent TEXT,
    document_url TEXT
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE geradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE consumidores ENABLE ROW LEVEL SECURITY;
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE comissoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_agreements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
CREATE POLICY "Admins can view all profiles" ON profiles FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Users can view own subscriptions" ON assinaturas;
CREATE POLICY "Users can view own subscriptions" ON assinaturas FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins can view all subscriptions" ON assinaturas;
CREATE POLICY "Admins can view all subscriptions" ON assinaturas FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Users can view own payments" ON pagamentos;
CREATE POLICY "Users can view own payments" ON pagamentos FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins can view all payments" ON pagamentos;
CREATE POLICY "Admins can view all payments" ON pagamentos FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Embaixadores can view own commissions" ON comissoes;
CREATE POLICY "Embaixadores can view own commissions" ON comissoes FOR SELECT USING (auth.uid() = embaixador_id);
DROP POLICY IF EXISTS "Admins can view all commissions" ON comissoes;
CREATE POLICY "Admins can view all commissions" ON comissoes FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Users can view own agreements" ON payment_agreements;
CREATE POLICY "Users can view own agreements" ON payment_agreements FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own agreements" ON payment_agreements;
CREATE POLICY "Users can insert own agreements" ON payment_agreements FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_leads_updated_at ON leads;
CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_geradores_updated_at ON geradores;
CREATE TRIGGER update_geradores_updated_at BEFORE UPDATE ON geradores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_consumidores_updated_at ON consumidores;
CREATE TRIGGER update_consumidores_updated_at BEFORE UPDATE ON consumidores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_assinaturas_updated_at ON assinaturas;
CREATE TRIGGER update_assinaturas_updated_at BEFORE UPDATE ON assinaturas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_comissoes_updated_at ON comissoes;
CREATE TRIGGER update_comissoes_updated_at BEFORE UPDATE ON comissoes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS update_pagamentos_updated_at ON pagamentos;
CREATE TRIGGER update_pagamentos_updated_at BEFORE UPDATE ON pagamentos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_profiles_tipo ON profiles(tipo);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_tipo ON leads(tipo);
CREATE INDEX IF NOT EXISTS idx_leads_user_id ON leads(user_id);
CREATE INDEX IF NOT EXISTS idx_geradores_status ON geradores(status);
CREATE INDEX IF NOT EXISTS idx_assinaturas_user_id ON assinaturas(user_id);
CREATE INDEX IF NOT EXISTS idx_assinaturas_status ON assinaturas(status);
CREATE INDEX IF NOT EXISTS idx_comissoes_embaixador_id ON comissoes(embaixador_id);
CREATE INDEX IF NOT EXISTS idx_comissoes_cliente_id ON comissoes(cliente_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_user_id ON pagamentos(user_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_status ON pagamentos(status);
CREATE INDEX IF NOT EXISTS idx_payment_agreements_user ON payment_agreements(user_id);

ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS agreed_to_payment_terms_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_terms_version TEXT;

ALTER TABLE match_proposals
    ADD COLUMN IF NOT EXISTS commissions_processed_at TIMESTAMPTZ;

ALTER TABLE pagamentos
    ADD COLUMN IF NOT EXISTS commissions_processed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ufv_fee_paid BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS embaixador_fee_paid BOOLEAN NOT NULL DEFAULT false;

CREATE OR REPLACE FUNCTION record_payment_agreement(
    p_user_id UUID, p_terms_version TEXT, p_terms_hash TEXT,
    p_ip_address INET DEFAULT NULL, p_user_agent TEXT DEFAULT NULL,
    p_document_url TEXT DEFAULT NULL
) RETURNS TABLE(already_accepted BOOLEAN, agreement_id UUID, accepted_at TIMESTAMPTZ) AS $$
DECLARE
    v_existing payment_agreements%ROWTYPE;
    v_new payment_agreements%ROWTYPE;
BEGIN
    SELECT * INTO v_existing FROM payment_agreements
    WHERE user_id = p_user_id AND terms_version = p_terms_version
    ORDER BY accepted_at DESC LIMIT 1;

    IF v_existing.id IS NOT NULL THEN
        RETURN QUERY SELECT TRUE, v_existing.id, v_existing.accepted_at;
        RETURN;
    END IF;

    INSERT INTO payment_agreements (user_id, terms_version, terms_hash, ip_address, user_agent, document_url)
    VALUES (p_user_id, p_terms_version, p_terms_hash, p_ip_address, p_user_agent, p_document_url)
    RETURNING * INTO v_new;

    UPDATE profiles
    SET agreed_to_payment_terms_at = v_new.accepted_at,
        last_terms_version = p_terms_version
    WHERE id = p_user_id
      AND (agreed_to_payment_terms_at IS NULL OR last_terms_version IS DISTINCT FROM p_terms_version);

    RETURN QUERY SELECT FALSE, v_new.id, v_new.accepted_at;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION process_match_commissions(p_proposal_id BIGINT)
RETURNS TABLE(success BOOLEAN, message TEXT, coins_credited INTEGER, inviter_credited INTEGER) AS $$
DECLARE
    v_proposal match_proposals%ROWTYPE;
    v_inviter_id UUID;
    v_total_credited INTEGER := 0;
    v_inviter_credited INTEGER := 0;
    v_result RECORD;
BEGIN
    SELECT * INTO v_proposal FROM match_proposals WHERE id = p_proposal_id FOR UPDATE;
    IF v_proposal.id IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Proposta nao encontrada'::TEXT, 0, 0;
        RETURN;
    END IF;
    IF v_proposal.commissions_processed_at IS NOT NULL THEN
        RETURN QUERY SELECT TRUE, 'Comissoes ja processadas'::TEXT, 0, 0;
        RETURN;
    END IF;
    IF v_proposal.status <> 'accepted' THEN
        RETURN QUERY SELECT FALSE, 'Proposta nao esta aceita'::TEXT, 0, 0;
        RETURN;
    END IF;

    INSERT INTO coin_wallet (user_id, balance) VALUES (v_proposal.from_user_id, 0) ON CONFLICT DO NOTHING;
    INSERT INTO coin_wallet (user_id, balance) VALUES (v_proposal.to_user_id, 0) ON CONFLICT DO NOTHING;

    SELECT * INTO v_result FROM credit_wallet(
        v_proposal.from_user_id, 20, 'bonus'::coin_transaction_type,
        'Bonus por match aceito #' || v_proposal.id, NULL, NULL, NULL,
        'match', v_proposal.id::TEXT,
        jsonb_build_object('role', 'from_user', 'counterpart', v_proposal.to_user_id)
    );
    v_total_credited := v_total_credited + 20;

    SELECT * INTO v_result FROM credit_wallet(
        v_proposal.to_user_id, 20, 'bonus'::coin_transaction_type,
        'Bonus por match aceito #' || v_proposal.id, NULL, NULL, NULL,
        'match', v_proposal.id::TEXT,
        jsonb_build_object('role', 'to_user', 'counterpart', v_proposal.from_user_id)
    );
    v_total_credited := v_total_credited + 20;

    SELECT referred_by INTO v_inviter_id FROM profiles
    WHERE id = COALESCE(v_proposal.to_user_id, v_proposal.from_user_id);

    IF v_inviter_id IS NOT NULL THEN
        INSERT INTO coin_wallet (user_id, balance) VALUES (v_inviter_id, 0) ON CONFLICT DO NOTHING;
        SELECT * INTO v_result FROM credit_wallet(
            v_inviter_id, 20, 'bonus'::coin_transaction_type,
            'Bonus por match na rede #' || v_proposal.id, NULL, NULL, NULL,
            'match', v_proposal.id::TEXT,
            jsonb_build_object('role', 'inviter')
        );
        v_inviter_credited := 20;
    END IF;

    UPDATE match_proposals SET commissions_processed_at = NOW() WHERE id = p_proposal_id;

    RETURN QUERY SELECT TRUE, 'Comissoes processadas'::TEXT, v_total_credited, v_inviter_credited;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION process_payment_commissions(p_payment_id BIGINT)
RETURNS TABLE(success BOOLEAN, message TEXT, embaixador_commission DECIMAL, ufv_commission DECIMAL) AS $$
DECLARE
    v_pag pagamentos%ROWTYPE;
    v_cliente profiles%ROWTYPE;
    v_embaixador_comissao DECIMAL(10,2) := 0;
    v_ufv_comissao DECIMAL(10,2) := 0;
    v_gerador_id UUID;
BEGIN
    SELECT * INTO v_pag FROM pagamentos WHERE id = p_payment_id FOR UPDATE;
    IF v_pag.id IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Pagamento nao encontrado'::TEXT, 0, 0;
        RETURN;
    END IF;
    IF v_pag.status <> 'succeeded' THEN
        RETURN QUERY SELECT FALSE, 'Pagamento nao foi confirmado'::TEXT, 0, 0;
        RETURN;
    END IF;
    IF v_pag.commissions_processed_at IS NOT NULL THEN
        RETURN QUERY SELECT TRUE, 'Comissoes ja processadas'::TEXT, 0, 0;
        RETURN;
    END IF;

    SELECT * INTO v_cliente FROM profiles WHERE id = v_pag.user_id;
    IF v_cliente.id IS NULL THEN
        RETURN QUERY SELECT FALSE, 'Perfil nao encontrado'::TEXT, 0, 0;
        RETURN;
    END IF;

    IF v_cliente.referred_by IS NOT NULL THEN
        v_embaixador_comissao := ROUND((v_pag.valor * 5) / 100, 2);
        INSERT INTO comissoes (embaixador_id, cliente_id, valor_comissao, percentual, tipo_comissao, status_pagamento, stripe_payment_intent, data_pagamento, mes_referencia, ano_referencia)
        VALUES (v_cliente.referred_by, v_pag.user_id, v_embaixador_comissao, 5, 'embaixador_5pct', 'pago', v_pag.stripe_payment_intent, NOW(), date_trunc('month', NOW())::date, EXTRACT(year FROM NOW())::integer);
    END IF;

    IF v_cliente.tipo = 'consumidor' THEN
        SELECT to_user_id INTO v_gerador_id FROM match_proposals
        WHERE from_user_id = v_pag.user_id AND status = 'accepted'
        ORDER BY responded_at DESC LIMIT 1;

        IF v_gerador_id IS NOT NULL THEN
            v_ufv_comissao := ROUND((v_pag.valor * 15) / 100, 2);
            INSERT INTO comissoes (embaixador_id, cliente_id, valor_comissao, percentual, tipo_comissao, status_pagamento, stripe_payment_intent, data_pagamento, mes_referencia, ano_referencia)
            VALUES (v_gerador_id, v_pag.user_id, v_ufv_comissao, 15, 'ufv_15pct', 'pago', v_pag.stripe_payment_intent, NOW(), date_trunc('month', NOW())::date, EXTRACT(year FROM NOW())::integer);
        END IF;
    END IF;

    UPDATE pagamentos
    SET commissions_processed_at = NOW(),
        ufv_fee_paid = (v_ufv_comissao > 0),
        embaixador_fee_paid = (v_embaixador_comissao > 0)
    WHERE id = p_payment_id;

    RETURN QUERY SELECT TRUE, 'Comissoes processadas'::TEXT, v_embaixador_comissao, v_ufv_comissao;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
