-- =====================================================
-- ENERGIALIVRE — Migration 20260111 (BOOTSTRAP)
-- Cria todas as tabelas que deveriam existir pelo schema.sql
-- caso o usuario nao tenha rodado o schema original.
-- Idempotente: use CREATE TABLE IF NOT EXISTS.
-- Cole no Supabase SQL Editor → New query → Run
-- =====================================================

-- =====================================================
-- 0. EXTENSOES
-- =====================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =====================================================
-- 1. FUNCAO AUXILIAR: update_updated_at
-- =====================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =====================================================
-- 2. TABELAS CORE (todas com IF NOT EXISTS)
-- =====================================================

-- PROFILES
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('consumidor', 'gerador', 'parceiro', 'admin')),
    role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    whatsapp TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS idx_profiles_tipo ON profiles(tipo);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);

-- LEADS
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('consumidor', 'gerador', 'parceiro')),
    capacidade_kwp FLOAT,
    gasto_mensal FLOAT,
    concessionaria TEXT,
    nicho TEXT,
    audiencia_estimada INTEGER,
    canal TEXT,
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'recusado')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    processed_by UUID REFERENCES profiles(id),
    observacoes TEXT,
    embaixador_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_tipo ON leads(tipo);
CREATE INDEX IF NOT EXISTS idx_leads_user_id ON leads(user_id);
CREATE INDEX IF NOT EXISTS idx_leads_embaixador ON leads(embaixador_id);

-- GERADORES
CREATE TABLE IF NOT EXISTS geradores (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    nome_usina TEXT NOT NULL,
    capacidade_kwp FLOAT NOT NULL CHECK (capacidade_kwp > 0),
    excedente_mensal_kwh FLOAT NOT NULL CHECK (excedente_mensal_kwh > 0),
    concessionaria TEXT NOT NULL,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL,
    endereco TEXT,
    latitude FLOAT,
    longitude FLOAT,
    status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'aprovado', 'ativo', 'inativo')),
    data_aprovacao TIMESTAMPTZ,
    lucro_total DECIMAL(12,2) DEFAULT 0.00,
    kwh_vendidos_total INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_geradores_status ON geradores(status);

-- CONSUMIDORES
CREATE TABLE IF NOT EXISTS consumidores (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    gasto_mensal FLOAT NOT NULL CHECK (gasto_mensal > 0),
    economia_mensal DECIMAL(10,2) DEFAULT 0.00,
    economia_total DECIMAL(12,2) DEFAULT 0.00,
    kwh_consumidos INTEGER DEFAULT 0,
    co2_evitado_kg INTEGER DEFAULT 0,
    arvores_salvas INTEGER DEFAULT 0,
    plano_ativo BOOLEAN DEFAULT false,
    data_primeira_assinatura TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ASSINATURAS
CREATE TABLE IF NOT EXISTS assinaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    stripe_subscription_id TEXT UNIQUE NOT NULL,
    stripe_price_id TEXT NOT NULL,
    nome_plano TEXT NOT NULL,
    valor_mensal DECIMAL(10,2) NOT NULL,
    kwh_mensais INTEGER NOT NULL,
    economia_percentual INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'past_due', 'canceled', 'unpaid')),
    current_period_start TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ NOT NULL,
    cancel_at_period_end BOOLEAN DEFAULT false,
    trial_end TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    canceled_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_assinaturas_user_id ON assinaturas(user_id);
CREATE INDEX IF NOT EXISTS idx_assinaturas_status ON assinaturas(status);

-- COMISSOES
CREATE TABLE IF NOT EXISTS comissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    embaixador_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    cliente_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
    valor_comissao DECIMAL(10,2) NOT NULL,
    percentual INTEGER NOT NULL CHECK (percentual > 0 AND percentual <= 100),
    tipo_comissao TEXT NOT NULL CHECK (tipo_comissao IN ('cadastro', 'recorrente', 'match', 'embaixador_5pct', 'ufv_15pct')),
    status_pagamento TEXT NOT NULL DEFAULT 'pendente' CHECK (status_pagamento IN ('pendente', 'pago', 'cancelado')),
    data_pagamento TIMESTAMPTZ,
    stripe_payment_intent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mes_referencia DATE NOT NULL DEFAULT date_trunc('month', NOW())::date,
    ano_referencia INTEGER NOT NULL DEFAULT EXTRACT(year FROM NOW())::integer
);
CREATE INDEX IF NOT EXISTS idx_comissoes_embaixador_id ON comissoes(embaixador_id);
CREATE INDEX IF NOT EXISTS idx_comissoes_cliente_id ON comissoes(cliente_id);
CREATE INDEX IF NOT EXISTS idx_comissoes_status_pagamento ON comissoes(status_pagamento);
CREATE INDEX IF NOT EXISTS idx_comissoes_tipo_comissao ON comissoes(tipo_comissao);

-- PAGAMENTOS
CREATE TABLE IF NOT EXISTS pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tipo_pagamento TEXT NOT NULL CHECK (tipo_pagamento IN ('assinatura', 'comissao', 'adicional')),
    valor DECIMAL(10,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'succeeded', 'failed', 'refunded')),
    stripe_payment_intent TEXT UNIQUE,
    stripe_charge_id TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_pagamentos_user_id ON pagamentos(user_id);
CREATE INDEX IF NOT EXISTS idx_pagamentos_tipo_pagamento ON pagamentos(tipo_pagamento);
CREATE INDEX IF NOT EXISTS idx_pagamentos_status ON pagamentos(status);
CREATE INDEX IF NOT EXISTS idx_pagamentos_created_at ON pagamentos(created_at DESC);

-- MATCHES
CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gerador_id UUID REFERENCES geradores(id) ON DELETE CASCADE,
    consumidor_id UUID REFERENCES consumidores(id) ON DELETE CASCADE,
    kwh_alocados INTEGER NOT NULL,
    valor_transacao DECIMAL(10,2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed', 'cancelled')),
    data_inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_fim TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_matches_gerador_id ON matches(gerador_id);
CREATE INDEX IF NOT EXISTS idx_matches_consumidor_id ON matches(consumidor_id);

-- ADMINS
CREATE TABLE IF NOT EXISTS admins (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'super_admin')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- 3. RLS (habilitar em todas)
-- =====================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE geradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE consumidores ENABLE ROW LEVEL SECURITY;
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;
ALTER TABLE comissoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pagamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;

-- Politicas basicas (somente leitura para o dono)
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
CREATE POLICY "Admins can view all profiles" ON profiles FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Users can view own subscriptions" ON assinaturas;
CREATE POLICY "Users can view own subscriptions" ON assinaturas FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can view all subscriptions" ON assinaturas;
CREATE POLICY "Admins can view all subscriptions" ON assinaturas FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Users can view own payments" ON pagamentos;
CREATE POLICY "Users can view own payments" ON pagamentos FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can view all payments" ON pagamentos;
CREATE POLICY "Admins can view all payments" ON pagamentos FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

DROP POLICY IF EXISTS "Embaixadores can view own commissions" ON comissoes;
CREATE POLICY "Embaixadores can view own commissions" ON comissoes FOR SELECT USING (auth.uid() = embaixador_id);

DROP POLICY IF EXISTS "Admins can view all commissions" ON comissoes;
CREATE POLICY "Admins can view all commissions" ON comissoes FOR ALL USING (EXISTS (SELECT 1 FROM admins WHERE id = auth.uid()));

-- =====================================================
-- 4. TRIGGERS DE updated_at
-- =====================================================
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_leads_updated_at ON leads;
CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_geradores_updated_at ON geradores;
CREATE TRIGGER update_geradores_updated_at BEFORE UPDATE ON geradores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_consumidores_updated_at ON consumidores;
CREATE TRIGGER update_consumidores_updated_at BEFORE UPDATE ON consumidores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_assinaturas_updated_at ON assinaturas;
CREATE TRIGGER update_assinaturas_updated_at BEFORE UPDATE ON assinaturas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_comissoes_updated_at ON comissoes;
CREATE TRIGGER update_comissoes_updated_at BEFORE UPDATE ON comissoes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_pagamentos_updated_at ON pagamentos;
CREATE TRIGGER update_pagamentos_updated_at BEFORE UPDATE ON pagamentos FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 5. TRIGGER: handle_new_user (cria profile no signup)
-- =====================================================
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, nome, tipo, role, whatsapp, cidade, estado)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'nome', NEW.email),
        COALESCE(NEW.raw_user_meta_data->>'tipo', 'consumidor'),
        'user',
        COALESCE(NEW.raw_user_meta_data->>'whatsapp', ''),
        COALESCE(NEW.raw_user_meta_data->>'cidade', ''),
        COALESCE(NEW.raw_user_meta_data->>'estado', '')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ language 'plpgsql' SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- =====================================================
-- 6. FUNCAO ADMIN CHECK (usada por RLS policies)
-- =====================================================
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM admins WHERE id = auth.uid());
END;
$$ language 'plpgsql' SECURITY DEFINER STABLE;

COMMENT ON TABLE comissoes IS 'Comissoes: cadastro, recorrente, match, embaixador_5pct, ufv_15pct.';
COMMENT ON TABLE pagamentos IS 'Historico de pagamentos (assinatura, comissao, adicional).';
COMMENT ON TABLE profiles IS 'Perfis de usuarios. 1:1 com auth.users.';
COMMENT ON TABLE leads IS 'Oportunidades de negocio (topo do funil).';
COMMENT ON TABLE admins IS 'Usuarios com permissao de admin.';
